data:
  name: figer
  data_files:
    train: data/figer/figer_train.json
    val: data/figer/figer_dev.json
    test: data/figer/figer_test.json
  label_path: data/ontology/figer_types.txt
  train_batch_size: 128
  eval_batch_size: 1024
  max_length: 128
  neg_batch_factor: 3

model:
  model_name: roberta-large
  head_dropout_prob: 0.5
  num_classes: 1
  threshold_step: 0.005
  optimizer_params:
    encoder:
      lr: 0.000005
      weight_decay: 0.01
    classifier:
      lr: 0.0005
      weight_decay: 0.01
  scheduler_params:
    scheduler_type: linear_warmup
    warmup: 0.1
  use_label_mean: True

trainer:
  max_epochs: 1
  val_check_interval: 0.01
