data:
  name: ufet
  data_files:
    train: data/ufet/el_train_processed.json
    val: data/ufet/ufet_dev.json
    test: data/ufet/ufet_test.json
  label_path: data/ontology/ufet_types.txt
  train_batch_size: 64
  eval_batch_size: 5200
  max_length: 128
  should_reduce_labels: False
  neg_batch_factor: 7

model:
  model_name: roberta-large
  head_dropout_prob: 0.5
  num_classes: 1
  threshold_step: 0.01
  threshold_log_file: thresholds.csv
  optimizer_params:
    encoder:
      lr: 0.000001
      weight_decay: 0.01
    classifier:
      lr: 0.0001
      weight_decay: 0.01
  scheduler_params:
    scheduler_type: constant_warmup
    warmup: 0.05
  use_label_mean: False

trainer:
  max_epochs: 2
  val_check_interval: 0.05
